services:
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  yente:
    image: ghcr.io/opensanctions/yente:5.5.0
    depends_on:
      index:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      YENTE_INDEX_TYPE: elasticsearch
      YENTE_INDEX_URL: http://index:9200
      YENTE_MANIFEST: /data/manifest.yml
      YENTE_INDEX_NAME: wa-m12b
    volumes:
      - ./artifacts/yente-benchmark:/data:ro
